FROM python:3.10

WORKDIR /app

COPY ./src ./src/
COPY ./app ./app/
COPY requirements.txt ./

RUN pip install --no-cache-dir -U -r requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]