# Imagem base
FROM python:3.10

# Diretório de trabalho
WORKDIR /app

# Copiar arquivos de código
COPY ./app ./app/
COPY ./src ./src/
COPY requirements.txt ./

# Instalar dependências
RUN pip install --no-cache-dir -U -r requirements.txt

# Expor porta do FastAPI
EXPOSE 8000

# Comando para rodar o FastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]